// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupR9zf1RzkHoAlrzlMrtFZoSJgesHFxk',
    appId: '1:743236155057:web:37123c788a81e163411490',
    messagingSenderId: '743236155057',
    projectId: 'chat-app-9bcce',
    authDomain: 'chat-app-9bcce.firebaseapp.com',
    storageBucket: 'chat-app-9bcce.appspot.com',
    measurementId: 'G-5LYW08GHT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACM4FcFz3KJjpXxXR2fY4ll6o1Y3mm9aw',
    appId: '1:743236155057:android:5265fa9f905c32c4411490',
    messagingSenderId: '743236155057',
    projectId: 'chat-app-9bcce',
    storageBucket: 'chat-app-9bcce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2_AmL7YRyw03-4_psvnNRzX23RvNPvw',
    appId: '1:743236155057:ios:7d901b64251fba3c411490',
    messagingSenderId: '743236155057',
    projectId: 'chat-app-9bcce',
    storageBucket: 'chat-app-9bcce.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2_AmL7YRyw03-4_psvnNRzX23RvNPvw',
    appId: '1:743236155057:ios:8a09ae40f93cb79f411490',
    messagingSenderId: '743236155057',
    projectId: 'chat-app-9bcce',
    storageBucket: 'chat-app-9bcce.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
